# Generated by Django 5.2 on 2025-05-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0003_reddit_scheduled_time_reddit_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegram",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
