# Generated by Django 5.2 on 2025-05-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0004_alter_telegram_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegram",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
