# Generated by Django 5.2 on 2025-05-13 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0005_telegram_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegram",
            name="chat_id",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
