# Generated by Django 5.2 on 2025-05-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0006_telegram_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reddit",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
