# Generated by Django 5.2 on 2025-05-14 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0008_redditaccount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redditaccount",
            name="reddit_username",
        ),
    ]
