# Generated by Django 5.2 on 2025-05-14 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0009_remove_redditaccount_reddit_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reddit",
            name="password",
        ),
        migrations.RemoveField(
            model_name="reddit",
            name="username",
        ),
    ]
