# Generated by Django 5.2 on 2025-05-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0011_redditaccount_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="reddit",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="reddit_photos/"),
        ),
        migrations.AddField(
            model_name="reddit",
            name="photo_url",
            field=models.TextField(blank=True),
        ),
    ]
