# Generated by Django 5.2 on 2025-05-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0013_alter_reddit_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reddit",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
