# Generated by Django 5.2 on 2025-05-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0014_alter_reddit_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reddit",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
